In [1]:
import pandas as pd

In [3]:
meta = pd.read_csv('../homeo/metadata.tsv', sep='\t')

In [4]:
meta

,sample_name,total_templates,total_reads,productive_templates,total_productive_reads,fraction_productive,total_rearrangements,productive_rearrangements,productive_simpson_clonality,max_productive_frequency,locus,sample_tags,sku,test_name
0,D238_ILN_CD8_NAIVE,4128,128712,3401,106069,0.8239,4051,3405,0.0257,0.003922,TCRB,"18-24 Years (Early Adulthood), 18-35 Years, 20...",NaN,NaN
1,D149_SP_CD8_NAIVE,59031,497976,48594,409933,0.8232,53930,44667,0.0065,0.000371,TCRB,"45-65 Years (Late Adulthood), 55 Years, 55-59 ...",NaN,NaN
2,D149_SP_CD4_NAIVE,64096,1347714,52000,1093387,0.8113,60522,49361,0.0060,0.000173,TCRB,"45-65 Years (Late Adulthood), 55 Years, 55-59 ...",NaN,NaN
3,D149_ILN_CD4_NAIVE,74561,1064078,60810,867845,0.8156,70972,58033,0.0052,0.000207,TCRB,"45-65 Years (Late Adulthood), 55 Years, 55-59 ...",NaN,NaN
4,D238_SP_CD8_NAIVE,18938,234665,16094,199431,0.8498,18777,16302,0.0161,0.002332,TCRB,"18-24 Years (Early Adulthood), 18-35 Years, 20...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,D72_SP_CD4_TEM,na,7893869,na,6545337,0.8292,43991,34293,0.0146,0.005528,TCRB,"18-35 Years, 24-45 Years (Middle Adulthood), 3...",NaN,NaN
112,D72_LLN_CD8_TEM,na,8331978,na,6664233,0.7998,12079,8792,0.1926,0.187008,TCRB,"18-35 Years, 24-45 Years (Middle Adulthood), 3...",NaN,NaN
113,D72_LLN_CD4_TEM,na,8316148,na,6960009,0.8369,37372,29309,0.0094,0.002947,TCRB,"18-35 Years, 24-45 Years (Middle Adulthood), 3...",NaN,NaN
114,D72_ILN_CD8_TEM,na,5142823,na,4059563,0.7894,10486,7712,0.0502,0.027191,TCRB,"18-35 Years, 24-45 Years (Middle Adulthood), 3...",NaN,NaN
115,D72_ILN_CD4_TEM,na,8406919,na,6992432,0.8317,34579,26712,0.0102,0.003401,TCRB,"18-35 Years, 24-45 Years (Middle Adulthood), 3...",NaN,NaN

In [7]:
meta = meta[meta.sample_name.str.contains('CD8_NAIVE')]
meta

,sample_name,total_templates,total_reads,productive_templates,total_productive_reads,fraction_productive,total_rearrangements,productive_rearrangements,productive_simpson_clonality,max_productive_frequency,locus,sample_tags,sku,test_name
0,D238_ILN_CD8_NAIVE,4128,128712,3401,106069,0.8239,4051,3405,0.0257,0.003922,TCRB,"18-24 Years (Early Adulthood), 18-35 Years, 20...",NaN,NaN
1,D149_SP_CD8_NAIVE,59031,497976,48594,409933,0.8232,53930,44667,0.0065,0.000371,TCRB,"45-65 Years (Late Adulthood), 55 Years, 55-59 ...",NaN,NaN
4,D238_SP_CD8_NAIVE,18938,234665,16094,199431,0.8498,18777,16302,0.0161,0.002332,TCRB,"18-24 Years (Early Adulthood), 18-35 Years, 20...",NaN,NaN
5,D238_LLN_CD8_NAIVE,4088,42021,2880,29613,0.7045,3989,3417,0.0547,0.018100,TCRB,"18-24 Years (Early Adulthood), 18-35 Years, 20...",NaN,NaN
17,D194_ILN_CD8_NAIVE,45629,810547,39563,702803,0.8671,44089,37971,0.0065,0.000953,TCRB,"45-65 Years (Late Adulthood), 50-54 Years, 53 ...",NaN,NaN
18,D194_LLN_CD8_NAIVE,56449,780075,49345,681905,0.8742,52403,45344,0.0065,0.001182,TCRB,"45-65 Years (Late Adulthood), 50-54 Years, 53 ...",NaN,NaN
22,D201_ILN_CD8_NAIVE,60418,935616,51968,804772,0.8601,58982,50190,0.0054,0.000537,TCRB,"18-24 Years (Early Adulthood), 18-35 Years, 20...",NaN,NaN
26,D201_LLN_CD8_NAIVE_3,45766,963708,39318,827943,0.8591,44732,38057,0.0068,0.000818,TCRB,"18-24 Years (Early Adulthood), 18-35 Years, 20...",NaN,NaN
32,D201_LLN_CD8_NAIVE_1,50735,813787,43507,697863,0.8575,49337,41994,0.0061,0.000559,TCRB,"18-24 Years (Early Adulthood), 18-35 Years, 20...",NaN,NaN
33,D201_LLN_CD8_NAIVE_2,52398,1002635,44820,857646,0.8554,51362,43542,0.0059,0.000479,TCRB,"18-24 Years (Early Adulthood), 18-35 Years, 20...",NaN,NaN
34,D201_SP_CD8_NAIVE,66170,740419,57403,642324,0.8675,62451,53705,0.0058,0.001087,TCRB,"18-24 Years (Early Adulthood), 18-35 Years, 20...",NaN,NaN
37,D200_SP_CD8_NAIVE,3668,67258,2798,51313,0.7628,3284,2482,0.0373,0.027186,TCRB,"45-65 Years (Late Adulthood), 55 Years, 55-59 ...",NaN,NaN
41,D200_LLN_CD8_NAIVE_1,12546,196061,9895,154636,0.7887,11732,9286,0.0163,0.008252,TCRB,"45-65 Years (Late Adulthood), 55 Years, 55-59 ...",NaN,NaN
42,D200_LLN_CD8_NAIVE_2,14888,260960,11961,209663,0.8034,13716,10979,0.0161,0.009358,TCRB,"45-65 Years (Late Adulthood), 55 Years, 55-59 ...",NaN,NaN
44,D200_ILN_CD8_NAIVE,1368,53972,908,35830,0.6637,1302,894,0.0430,0.014876,TCRB,"45-65 Years (Late Adulthood), 55 Years, 55-59 ...",NaN,NaN
47,D194_SP_CD8_NAIVE,11197,365490,8919,291142,0.7966,9337,7786,0.0731,0.062825,TCRB,"45-65 Years (Late Adulthood), 50-54 Years, 53 ...",NaN,NaN
49,D194_LLN_CD8_NAIVE,3690,59804,3054,49503,0.8276,3674,3067,0.0227,0.001434,TCRB,"45-65 Years (Late Adulthood), 50-54 Years, 53 ...",NaN,NaN
51,D194_ILN_CD8_NAIVE,3468,115026,2830,93880,0.8160,3423,2771,0.0228,0.003014,TCRB,"45-65 Years (Late Adulthood), 50-54 Years, 53 ...",NaN,NaN
55,D141_ILN_CD8_NAIVE,12795,850614,10686,710430,0.8352,11418,9587,0.0363,0.031892,TCRB,"45-65 Years (Late Adulthood), 60-64 Years, 63 ...",NaN,NaN
56,D139_ILN_CD8_NAIVE,6560,201954,5213,160493,0.7947,6186,5162,0.0230,0.002548,TCRB,"24-45 Years (Middle Adulthood), 45-49 Years, 4...",NaN,NaN
58,D127_SP_CD8_NAIVE,26627,813724,21053,643407,0.7907,25249,20680,0.0100,0.000695,TCRB,"00-02 Years (Infancy), 01-04 Years, 16 Months,...",NaN,NaN
60,D127_LLN_CD8_NAIVE,21085,990908,16619,781025,0.7882,20385,16536,0.0111,0.001050,TCRB,"00-02 Years (Infancy), 01-04 Years, 16 Months,...",NaN,NaN
61,D127_ILN_CD8_NAIVE,8953,587212,7013,460020,0.7833,8635,6863,0.0169,0.001828,TCRB,"00-02 Years (Infancy), 01-04 Years, 16 Months,...",NaN,NaN
63,D125_SP_CD8_NAIVE,3466,166799,2736,131682,0.7894,3337,2657,0.0290,0.004929,TCRB,"45-65 Years (Late Adulthood), 50-54 Years, 51 ...",NaN,NaN
67,D115_SP_CD8_NAIVE,4973,427853,3867,332714,0.7776,4737,3756,0.0243,0.004088,TCRB,"02-12 (Childhood), 05 Years, 05-09 Years, CCR7...",NaN,NaN
68,D115_LLN_CD8_NAIVE,17570,705995,13730,551707,0.7814,16766,13466,0.0124,0.001080,TCRB,"02-12 (Childhood), 05 Years, 05-09 Years, Brac...",NaN,NaN
69,D115_ILN_CD8_NAIVE,7160,401327,5604,314150,0.7827,6789,5363,0.0191,0.002531,TCRB,"02-12 (Childhood), 05 Years, 05-09 Years, CCR7...",NaN,NaN
74,D100_ILN_CD8_NAIVE,17271,403336,14269,333247,0.8262,16748,13863,0.0115,0.001638,TCRB,"18-24 Years (Early Adulthood), 18-35 Years, 20...",NaN,NaN
75,D125_ILN_CD8_NAIVE,11216,326375,9296,270515,0.8288,10970,9179,0.0140,0.000939,TCRB,"45-65 Years (Late Adulthood), 50-54 Years, 51 ...",NaN,NaN
76,D106_ILN_CD8_NAIVE,37316,2190475,30296,1778450,0.8119,36578,29460,0.0081,0.000342,TCRB,"01-04 Years, 02-12 (Childhood), 04 Years, CCR7...",NaN,NaN
77,D99_ILN_CD8_NAIVE,15726,629135,13020,520918,0.8279,15392,12731,0.0113,0.002085,TCRB,"24-45 Years (Middle Adulthood), 45 Years, 45-4...",NaN,NaN

In [14]:
meta['hla'] = meta.sample_tags.apply(lambda x: ','.join([y.strip() for y in x.split(',') if 'A*' in y]))

/tmp/ipykernel_261760/4263005448.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  meta['hla'] = meta.sample_tags.apply(lambda x: ','.join([y.strip() for y in x.split(',') if 'A*' in y]))

In [20]:
selected_meta = meta[(meta.sample_name.str.contains('ILN')) & (meta.hla.str.contains('A*02'))]
selected_meta

,sample_name,total_templates,total_reads,productive_templates,total_productive_reads,fraction_productive,total_rearrangements,productive_rearrangements,productive_simpson_clonality,max_productive_frequency,locus,sample_tags,sku,test_name,hla
0,D238_ILN_CD8_NAIVE,4128,128712,3401,106069,0.8239,4051,3405,0.0257,0.003922,TCRB,"18-24 Years (Early Adulthood), 18-35 Years, 20...",NaN,NaN,"HLA-A*01,HLA-A*02"
22,D201_ILN_CD8_NAIVE,60418,935616,51968,804772,0.8601,58982,50190,0.0054,0.000537,TCRB,"18-24 Years (Early Adulthood), 18-35 Years, 20...",NaN,NaN,"HLA-A*02,HLA-A*33"
44,D200_ILN_CD8_NAIVE,1368,53972,908,35830,0.6637,1302,894,0.0430,0.014876,TCRB,"45-65 Years (Late Adulthood), 55 Years, 55-59 ...",NaN,NaN,HLA-A*02
74,D100_ILN_CD8_NAIVE,17271,403336,14269,333247,0.8262,16748,13863,0.0115,0.001638,TCRB,"18-24 Years (Early Adulthood), 18-35 Years, 20...",NaN,NaN,"HLA-A*02,HLA-A*32"

In [21]:
datasets_to_concat = []
for run in selected_meta.sample_name:
    data = pd.read_csv(f'../homeo/{run}.tsv', sep='\t')
    datasets_to_concat.append(data)

/tmp/ipykernel_261760/2715334457.py:3: DtypeWarning: Columns (81,82,83,88,93,99,100,101,104,105,112,115) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(f'../homeo/{run}.tsv', sep='\t')
/tmp/ipykernel_261760/2715334457.py:3: DtypeWarning: Columns (81,82,83,88,93,99,100,101,104,105,112,115) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(f'../homeo/{run}.tsv', sep='\t')

In [23]:
example_data = pd.read_csv(f'../homeo/D238_ILN_CD8_NAIVE.tsv', sep='\t')
example_data

,sample_name,species,locus,product_subtype,kit_pool,sku,test_name,sample_catalog_tags,sample_rich_tags,sample_rich_tags_json,...,cdr3_rearrangement,cdr3_amino_acid,cdr3_start_index,cdr3_rearrangement_length,chosen_v_family,chosen_v_gene,chosen_v_allele,chosen_j_family,chosen_j_gene,chosen_j_allele
0,D238_ILN_CD8_NAIVE,Human,TCRB,Survey,NaN,NaN,NaN,"Age (Range):18-24 Years (Early Adulthood),Age ...",NaN,[],...,TGTGCCAGCAGTTAGCCCCTCCGGGGGGGAAGCTCCTACGAGCAGT...,CASS*PLRGGSSYEQYF,NaN,51,NaN,NaN,NaN,NaN,NaN,NaN
1,D238_ILN_CD8_NAIVE,Human,TCRB,Survey,NaN,NaN,NaN,"Age (Range):18-24 Years (Early Adulthood),Age ...",NaN,[],...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
2,D238_ILN_CD8_NAIVE,Human,TCRB,Survey,NaN,NaN,NaN,"Age (Range):18-24 Years (Early Adulthood),Age ...",NaN,[],...,TGTGCCAGCAGCTTGGGACACATTGATGAAGCTTTCTTT,CASSLGHIDEAFF,327.0,39,TCRBV05,6.0,1.0,TCRBJ01,1.0,1.0
3,D238_ILN_CD8_NAIVE,Human,TCRB,Survey,NaN,NaN,NaN,"Age (Range):18-24 Years (Early Adulthood),Age ...",NaN,[],...,TGTGCCAGCAGCTTGGCCCTCGTGTCAGATACGCAGTATTTT,CASSLALVSDTQYF,327.0,42,TCRBV05,6.0,1.0,TCRBJ02,3.0,1.0
4,D238_ILN_CD8_NAIVE,Human,TCRB,Survey,NaN,NaN,NaN,"Age (Range):18-24 Years (Early Adulthood),Age ...",NaN,[],...,TGTGCCAGCAGCGCTAGTATCAAAAACATTCAGTACTTC,CASSASIKNIQYF,327.0,39,TCRBV05,6.0,1.0,TCRBJ02,4.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4046,D238_ILN_CD8_NAIVE,Human,TCRB,Survey,NaN,NaN,NaN,"Age (Range):18-24 Years (Early Adulthood),Age ...",NaN,[],...,TGTGCCAGCAGCGATACAGGGGGACAGCCCCAGCATTTT,CASSDTGGQPQHF,NaN,39,NaN,NaN,NaN,NaN,NaN,NaN
4047,D238_ILN_CD8_NAIVE,Human,TCRB,Survey,NaN,NaN,NaN,"Age (Range):18-24 Years (Early Adulthood),Age ...",NaN,[],...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
4048,D238_ILN_CD8_NAIVE,Human,TCRB,Survey,NaN,NaN,NaN,"Age (Range):18-24 Years (Early Adulthood),Age ...",NaN,[],...,TGTGCCAGCAGCCCGGGACAGTGGGCCAACTATGGCTACACCTTC,CASSPGQWANYGYTF,NaN,45,NaN,NaN,NaN,NaN,NaN,NaN
4049,D238_ILN_CD8_NAIVE,Human,TCRB,Survey,NaN,NaN,NaN,"Age (Range):18-24 Years (Early Adulthood),Age ...",NaN,[],...,TGCAGTGCTGACGGGTCTTTGGGGAATGAGCAGTTCTTC,CSADGSLGNEQFF,NaN,39,NaN,NaN,NaN,NaN,NaN,NaN
4050,D238_ILN_CD8_NAIVE,Human,TCRB,Survey,NaN,NaN,NaN,"Age (Range):18-24 Years (Early Adulthood),Age ...",NaN,[],...,TGTGCCACCTCCGGGACAGCGAACACTGAAGCTTTCTTT,CATSGTANTEAFF,NaN,39,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
example_data['total_rearrangements']

0       4051
1       4051
2       4051
3       4051
4       4051
        ...
4046    4051
4047    4051
4048    4051
4049    4051
4050    4051
Name: total_rearrangements, Length: 4051, dtype: int64

In [25]:
for col in example_data.columns:
    print(col)

sample_name
species
locus
product_subtype
kit_pool
sku
test_name
sample_catalog_tags
sample_rich_tags
sample_rich_tags_json
hla_class_i
hla_class_ii
kit_control
total_templates
productive_templates
outofframe_templates
stop_templates
dj_templates
total_rearrangements
productive_rearrangements
outofframe_rearrangements
stop_rearrangements
dj_rearrangements
total_reads
total_productive_reads
total_outofframe_reads
total_stop_reads
total_dj_reads
productive_simpson_clonality
productive_clonality
productive_entropy
sample_simpson_clonality
sample_clonality
sample_entropy
sample_amount_ng
sample_cells_mass_estimate
fraction_productive_of_cells_mass_estimate
sample_cells
fraction_productive_of_cells
max_productive_frequency
max_frequency
counting_method
primer_set
sequence_result_status
release_date
upload_date
sample_tags
fraction_productive
order_name
kit_id
total_t_cells
total_templates_agg
rearrangement
amino_acid
frame_type
rearrangement_type
templates
seq_reads
frequency
productive_frequency
cdr3_length
v_family
v_gene
v_allele
d_family
d_gene
d_allele
j_family
j_gene
j_allele
v_deletions
d5_deletions
d3_deletions
j_deletions
n2_insertions
n1_insertions
v_index
n1_index
n2_index
d_index
j_index
v_family_ties
v_gene_ties
v_allele_ties
d_family_ties
d_gene_ties
d_allele_ties
j_family_ties
j_gene_ties
j_allele_ties
sequence_tags
v_shm_count
v_shm_indexes
antibody
bio_identity
rearrangement_trunc
v_resolved
d_resolved
j_resolved
extended_rearrangement
cdr1_rearrangement
cdr1_amino_acid
cdr1_start_index
cdr1_rearrangement_length
cdr2_rearrangement
cdr2_amino_acid
cdr2_start_index
cdr2_rearrangement_length
cdr3_rearrangement
cdr3_amino_acid
cdr3_start_index
cdr3_rearrangement_length
chosen_v_family
chosen_v_gene
chosen_v_allele
chosen_j_family
chosen_j_gene
chosen_j_allele